name: Unified Profile Maintenance

on:
  schedule:
    - cron: '0 0,9,15,21 * * *'  # 4 раза в день (00:00, 09:00, 15:00, 21:00)
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-metrics:
    name: Update GitHub Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, activity, community
          filename: metrics.svg
          config_timezone: Europe/Moscow
          config_display: large
          config_twemoji: yes
          config_padding: 0, 10%

      - name: Generate GitHub contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg?color_snake=#58a6ff&color_dots=#ebedf0,#00FF88,#00E676,#00C853,#00A040
            github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#58a6ff&color_dots=#161b22,#00FF88,#00FF00,#76FF03,#B2FF59

      - name: Commit generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.svg
          git commit -m "🔄 Update contribution snake graphics" || echo "No changes to commit"
          git pull --rebase origin main  # Добавляем эту строку
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-readme:
    name: Update README Content
    needs: update-metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-dateutil requests

      - name: Update WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Run custom README update
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: python scripts/update_readme.py

      - name: Commit README changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Проверяем, есть ли изменения в README.md
          if git diff --quiet README.md; then
            echo "No changes in README.md."
            exit 0
          fi
          
          # Добавляем только README.md
          git add README.md
          
          # Коммитим изменения
          git commit -m "📝 Update README content [skip ci]"
          
          # Делаем pull с rebase перед push
          git pull --rebase
          
          # Пушим изменения
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}