name: Unified Profile Maintenance

on:
  schedule:
    - cron: '0 0,9,15,21 * * *'  # 4 раза в день (00:00, 09:00, 15:00, 21:00)
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-metrics:
    name: Update GitHub Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, activity, community
          config_timezone: Europe/Moscow
          filename: metrics.svg

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: dmitrij-el
          outputs: dist/github-contribution-grid-snake.svg

      - name: Generate and commit snake
        run: |
          cp -f dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          git add github-contribution-grid-snake.svg
          git commit -m "🔄 Update contribution snake" || echo "No snake changes"
        if: always()

      - name: Push all changes
        run: |
          git fetch origin main
          git reset --hard origin/main
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

  update-readme:
    name: Update README Content
    needs: update-metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-dateutil requests

      - name: Update WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Run custom README update
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/update_readme.py

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git pull origin main --rebase
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "📊 Unified profile update [skip ci]"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}