name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # каждый день
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: dmitrij-el
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}