name: summary-cards

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      gh_pat_push:
        required: true
      metrics_token:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.gh_pat_push }}
      PROFILE_REPO: dmitrij-el/dmitrij-el
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ inputs.username }}
          BRANCH_NAME: dev
          AUTO_PUSH: false
        env:
          GITHUB_TOKEN: ${{ secrets.metrics_token }}

      - name: Checkout profile repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.PROFILE_REPO }}
          token: ${{ secrets.gh_pat_push }}
          persist-credentials: true
          path: profile-repo

      - name: Clone current repo again to get cards
        run: |
          git clone --depth=1 https://${GH_PAT}@github.com/${GITHUB_OWNER}/${GITHUB_REPO_NAME}.git temp-cards
          mkdir -p profile-repo/profile-summary-card-output/${GITHUB_OWNER}/${GITHUB_REPO_NAME}
          cp -r temp-cards/profile-summary-card-output/* profile-repo/profile-summary-card-output/${GITHUB_OWNER}/${GITHUB_REPO_NAME}/ || echo "No cards"
          rm -rf temp-cards

      - name: Commit and push to profile
        run: |
          cd profile-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output/${GITHUB_OWNER}/${GITHUB_REPO_NAME}
          git commit -m "Sync summary cards from ${GITHUB_REPO_NAME}" || echo "Nothing to commit"
          git push origin main