name: GitHub Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # каждый день
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: dmitrij-el
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}